### ISSUE TITLE
Remove HK2 from dependencies

### ISSUE THREAD

**Issue by meshuga** [masterspambot/katharsis-rs#3]
Try to use some feasible DI mechanism which will allow using many libraries e.g. Guice or Dagger.

**Comment by ggwozdz** [comment]
Dagger seems to be very limiting - I strongly suggest [Guice](http://www.reddit.com/r/java/comments/1y9e6t/ama_were_the_google_team_behind_guava_dagger)

**Comment by meshuga** [comment]
@ggwozdz yes
